# Generated by Django 2.2 on 2019-03-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('date_of_birth', models.DateField(default='')),
                ('email', models.EmailField(default='', max_length=200)),
                ('create_username', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('confim_password', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
