# Generated by Django 2.2 on 2019-03-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0004_auto_20190313_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='relativeitemsmodel',
            name='photo',
            field=models.CharField(default='', max_length=2),
        ),
    ]
