# Generated by Django 2.2 on 2019-03-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0006_auto_20190314_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newusermodel',
            name='foreignkeyToUser',
        ),
        migrations.RemoveField(
            model_name='relativeitemsmodel',
            name='foreignkeyToUser',
        ),
        migrations.CreateModel(
            name='wikipostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('text', models.TextField(default='', max_length=200)),
                ('datecreated', models.DateField(default='', null=True)),
                ('lastupdate', models.DateField(default='', null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikiApp.newuserModel')),
            ],
        ),
        migrations.AddField(
            model_name='relativeitemsmodel',
            name='links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikiApp.wikipostModel'),
        ),
    ]
