# Generated by Django 2.2 on 2019-03-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0007_auto_20190314_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relativeitemsmodel',
            name='photo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
