# Generated by Django 2.2 on 2019-03-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0008_auto_20190315_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relativeitemsmodel',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
